name: Testing junit2html

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    init:
      name: Test junit2html
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@master
          - name: Initialize Python 3.8
            uses: actions/setup-python@v1
            with:
              python-version: 3.8
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pytest wheel
                python -m pip install -e .
          - name: Run Tests
            run: |
              python -m pytest -v . --junitxml=junit2html-job-${CI_JOB_NAME}.xml
              python -m junit2htmlreport junit2html-job-${CI_JOB_NAME}.xml
              python -m junit2htmlreport --report-matrix tests/matrix-example.html tests/junit-axis-linux.xml tests/junit-axis-solaris.xml tests/junit-axis-windows.xml
              python -m junit2htmlreport --merge junit2html-merged-example.xml tests/junit-unicode.xml tests/junit-unicode2.xml tests/junit-cute2.xml
              python -m junit2htmlreport junit2html-merged-example.xml
              python setup.py bdist_wheel
