name: Testing junit2html

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    AllVersions:
      name: Testing on Python
      runs-on: ubuntu-latest
      strategy:
          matrix:
            version: [3.6, 3.8, 3.9]
      steps:
          - uses: actions/checkout@master
          - name: Initialize Python ${{ matrix.version }}
            uses: actions/setup-python@v1
            with:
              python-version: ${{ matrix.version }}
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install pytest wheel
                python -m pip install -e .
          - name: Run Tests
            run: |
              python -m pytest -v . --junitxml=junit2html-job-${CI_JOB_NAME}.xml
              python -m junit2htmlreport junit2html-job-${CI_JOB_NAME}.xml
              python -m junit2htmlreport --report-matrix tests/matrix-example.html tests/junit-axis-linux.xml tests/junit-axis-solaris.xml tests/junit-axis-windows.xml
              python -m junit2htmlreport --merge junit2html-merged-example.xml tests/junit-unicode.xml tests/junit-unicode2.xml tests/junit-cute2.xml
              python -m junit2htmlreport junit2html-merged-example.xml
              python setup.py bdist_wheel
